### ISSUE TITLE
Incorrect minimal sample in README

### ISSUE THREAD

**Issue by TheCodeArtist** [superna9999/pyfdt#11]
README.md specifies Typical usage as:

```
from pyfdt import FdtBlobParse
with open("myfdt.dtb") as infile:
    dtb = FdtBlobParse(infile)
    print dtb.to_fdt().to_dts()
```

However this fails with the following error on my system:
```
Traceback (most recent call last):
  File "./test-fdt.py", line 8, in <module>
    dtb = pyfdt.FdtBlobParse(infile)
AttributeError: 'module' object has no attribute 'FdtBlobParse'

```

The import staement that works properly is the one given in the samples:
`from pyfdt.pyfdt import FdtBlobParse`

**Comment by TheCodeArtist** [comment]
Submitted pull request https://github.com/superna9999/pyfdt/pull/12 to fix this issue.

Please Review...

**Comment by superna9999** [comment]
Thanks for the PR, once the CI build finished I'll merge it
